version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  web1:
    image: crccheck/hello-world:latest
    container_name: web1
    expose:
      - "83"

  web2:
    image: crccheck/hello-world:latest
    container_name: web2
    expose:
      - "84"

  web3:
    image: crccheck/hello-world:latest
    container_name: web3
    expose:
      - "85"